### PR TITLE
noindex URI::tcp module

### PR DESCRIPTION
**Pull request by JaSei**
https://github.com/avast/URI-tcp/issues/1

https://rt.cpan.org/Public/Bug/Display.html?id=118554

### CODE REVIEW

**Comment by JaSei** [comment]
Hi, any progress with my PR? Thanks

**Comment by redhotpenguin** [comment]
Sorry for the delay on this - can you amend this to add entries to the CHANGES file also?

**Comment by redhotpenguin** [comment]
Nvm I got it - thanks!!

**Comment by JaSei** [comment]
Thanks a lot!

**Pull request merged**
