### PR TITLE
Report patch proposed in RT#78588

### PR DESCRIPTION
**Pull request by guimard**
Hi all,
here is a UTF-8 patch proposed to fix an UTF-8 problem. See https://rt.cpan.org/Public/Bug/Display.html?id=78588

### CODE REVIEW

**Comment by redhotpenguin** [comment]
Sure, this looks reasonable

**Comment by guimard** [comment]
Thanks !

**Comment by Grinnz** [comment]
This is not correct. utf8::is_utf8 should never be used this way. See https://github.com/tobyink/p5-html-html5-parser/pull/3 and https://github.com/perl5-dbi/DBD-mysql/issues/197 for past discussions enumerating the problems with this approach.

**Comment by karenetheridge** [comment]
I responded in the RT ticket with similar concerns. `is_utf8` does not do what you think it does here.

**Comment by redhotpenguin** [comment]
Open to additional changes here if needed. I noticed the use of is_utf8, but I leave the responsibility of correctness to the contributor.

**Comment by redhotpenguin** [comment]
After reading through the RT ticket, I think we need to remove the is_utf8() call. I'm committed another change to pull that, but leaving the test for `xsd:base64Binary` in place. Would welcome another change that basically tells the user to disable types as per the RT ticket.

**Comment by ams-tschoening** [comment]
`is_utf8` is fine to distinguish between a string of characters with current Perl using UTF-8 as underlying encoding and an arbitrary array of bytes.

> As a quick example, consider the string "Â".  what does is_utf8() return? Should it be considered encoded for the purposes of SOAP::Lite?

That is simply the wrong question, `is_utf8` totally depends on how some user stores the given example string. The string can be stored in Perls internal character string format, it can be stored as a byte array in UTF-8 encoding, it can be stored in LATIN-1 encoding, windows-1252 or something completely proprietary. That is not the point, the point is that IF `is_utf8` is true on some scalar, the user managed to tell Perl to treat some data as a string of characters from that point on and that is exactly what SOAP::Lite needs to know. Of course the user could have done something wrong in telling Perl, but that's the problem of the user, not SOAP::Lite. Garbage in, garbage out.

> But it encodes to "\x{c3}\x{82}". Is *that* utf8?

Yes it is:

> U+00C2 | 0xC2 | Â | Ã‚ | %C3 %82

http://www.i18nqa.com/debug/utf8-debug.html

> How do we know this is "Â" in utf8 encoding, vs. two characters, "Â" and an unprintable one?

Because the user told Perl so by either leaving something a byte array, so we can't know anything about the purpose of those two bytes and `is_utf8` is false, OR by using e.g. `utf8::decode` in case the user decided that those two bytes are valid UTF-8 and told Perl so, which can then be checked using `is_utf8` in SOAP::Lite. Perl might(!) decide to not enable the flag even then, which was the cas ein some versions of Perl for strict ASCII text, but that's not the problem of SOAP::Lite as well, because handling character strings and byte arrays doesn't change a thing in those cases.

> The sad truth is that *there is no way* of distinguishing characters from encoded text by merely inspecting its bytes.

Nobody does that in this case, `is_utf8` distinguishes between a user told Perl to have characters or bytes and that is exactly what SOAP::Lite cares about.

**Comment by Grinnz** [comment]
is_utf8 is not "the user" indicating anything. The utf8 bit may be set or unset at any time unintentionally, even by basic Perl operations like string concatenation. Depending on where it came from and what operations were done and what modules it went through, you can end up with a string with non-ascii characters with the utf8 bit set or unset, and an all-ascii string with the utf8 bit set or unset. Nothing except poorly-written XS code should be concerning itself with the internal state of a Perl string except to work around other poorly-written XS code.

**Comment by ams-tschoening** [comment]
Your argument breaks down to what I already said with "garbage in, garbage out", but that's the responsibility of the user, not SOAP::Lite. SOAP::Lite only needs to correctly handle character vs. byte strings it manages itself, it doesn't need to care if callers provide broken data. Of course things can go wrong if strings are concatenated with byte arrays, but that is simply an user error.

**Comment by Grinnz** [comment]
It is not the responsibility of the user to manage the internal encoding of Perl strings, this is just shoving off the problem to another level. Only XS code and code working around broken XS code (or Perl issues) should ever be messing with it or care. In normal operation whether a string is upgraded or downgraded does not change the value of that string at the Perl level. Perl does not have an indication of user intent for a string, APIs must be constructed to allow the user to specify this separately, end of story.

**Comment by ams-tschoening** [comment]
> It is not the responsibility of the user to manage the internal encoding of Perl strings, this is just shoving off the problem to another level.

It IS the responsibility of the user to decide if one wants to work with byte arrays or character strings and to tell Perl that decision using proper encoding functions. `is_utf8` is about that decision.

> In normal operation whether a string is upgraded or downgraded does not change the value of that string at the Perl level.

That is simply not true, just read the docs:

> (Since Perl v5.8.0) Converts in-place the internal representation of the string from an octet sequence in the native encoding (Latin-1 or EBCDIC) to UTF-8.

vs.

> (Since Perl v5.8.0) Converts in-place the internal representation of the string from UTF-8 to the equivalent octet sequence in the native encoding (Latin-1 or EBCDIC). 

If at all you are talking about `encode` and `decode` and those do change the semantics of the underlying scalar from either being a character string to a byte array or vice versa. That doesn't change a thing on what I told about `is_utf8`.

> Perl does not have an indication of user intent for a string, APIs must be constructed to allow the user to specify this separately, end of story.

You are wrong, you can read in various places that Perl itself distinguishes between byte arrays and character strings internally:

> (Since Perl v5.8.0) Converts in-place the **character sequence** to the corresponding octet sequence in UTF-8. 

> (Since Perl v5.8.0) Attempts to convert in-place the octet sequence encoded as UTF-8 to the corresponding **character sequence**.

Just think of the "wide character" warnings etc.

> Perl had to change internally to decouple "bytes" from "characters". It is important that you too change your ideas, if you haven't already, so that "byte" and "character" no longer mean the same thing in your mind.

https://perldoc.perl.org/perlunicode.html#Byte-and-Character-Semantics

**Comment by Grinnz** [comment]
I'm not sure what you're arguing with me about. Yes, the user must know whether they have a byte or character string, because the internal state of the string does not store this information, as I said.

**Comment by Grinnz** [comment]
Consider this: What if you encode a UTF-8-encoded byte string to UTF-8, intentionally? Both the input and output will have the utf8 flag off, because this is how the Perl internal storage works, but was the input characters or bytes when it comes to using it in APIs? It's completely up to the user.

**Comment by Grinnz** [comment]
I recommend that you read through this ticket that is referenced by the migrated issue I linked above, as schmorp has a very good understanding of Perl strings, particularly https://rt.cpan.org/Ticket/Display.html?id=87428#txn-1346009 .

**Comment by karenetheridge** [comment]
My favourite ticket that really helped the lightbulbs come on for me for utf8 is https://rt.cpan.org/Ticket/Display.html?id=104433.

**Comment by ams-tschoening** [comment]
> Yes, the user must know whether they have a byte or character string, because the internal state of the string does not store this information, as I said.

Which is wrong, Perl internally either has a byte array OR a character string and distinguishes that using the  UTF-8 flag and I even linked the relevant parts of the docs:

> String handling functions, for the most part, continue to operate in terms of characters. length(), for example, returns the number of characters in a string, just as before. But that number no longer is necessarily the same as the number of bytes in the string (there may be more bytes than characters). The other such functions include chop(), chomp(), substr(), pos(), index(), rindex(), sort(), sprintf(), and write().

With only looking at this paragraph, your claim would already be wrong because it makes absolutely clear that Perl does know of characters instead of bytes. Of course we know it knows of bytes as well, else one couldn't get the length of a byte array containing e.g. binary images.

> Like all Perl character operations, length normally deals in logical characters, not physical bytes. For how many bytes a string encoded as UTF-8 would take up, use length(Encode::encode('UTF-8', EXPR)) (you'll have to use Encode first). See Encode and perlunicode.

https://perldoc.perl.org/functions/length.html

Please explain that paragraph without Perl being able to distinguish bytes and characters if it clearly says that it is able to distinguish bytes and characters.

> What if you encode a UTF-8-encoded byte string to UTF-8, intentionally?

Nothing happens of course because you are dealing with byte arrays in both cases, your example doesn't make any sense and only proves that you didn't understand the difference between a byte array and a character string. The UTF-8 encoded byte string needs to be decoded first to get a character string and then one can encode it back to some arbitrary encoding.

> Both the input and output will have the utf8 flag off,

Of course, because you don't change a thing at the fact that you keep using byte arrays instead of character strings.

> because this is how the Perl internal storage works, but was the input characters or bytes when it comes to using it in APIs?

In your case it was clearly bytes as per you example definition and the lack of decoding it to a character string.

> https://rt.cpan.org/Ticket/Display.html?id=87428

If you think this ticket contains text proving me wrong, you should quote it.

**Comment by Grinnz** [comment]
> Nothing happens of course because you are dealing with byte arrays in both cases, your example doesn't make any sense and only proves that you didn't understand the difference between a byte array and a character string. The UTF-8 encoded byte string needs to be decoded first to get a chacaracter string and then one can encode it back to some arbitrary encoding.

Incorrect. You can encode a UTF-8 byte string to UTF-8, the result is a different UTF-8 encoded byte string, representing the double-encoding of the original characters. Each step is still a perfectly valid Perl string, and the single and double encoding of the characters are both perfectly valid byte strings. When encoding the UTF-8 encoded bytes to UTF-8, you are considering them (as Perl does) as Unicode codepoints.

> If you think this ticket contains text proving me wrong, you should quote it.

I edited it to more specifically reference the explanation that should help you understand what you are missing.

**Comment by karenetheridge** [comment]
> https://perldoc.perl.org/functions/length.html  
>   
> Please explain that paragraph without Perl being able to distinguish bytes and characters if it clearly says that it is able to distinguish bytes and characters.


```
use strict;
use warnings;
use utf8;   # signals that this file contains characters to be parsed as utf8-encoded

my $str = "ಠ_ಠ";
print length($str), "\n";

utf8::encode($str);
print length($str), "\n";
print $str, "\n";

utf8::upgrade($str);
print length($str), "\n";
print $str, "\n";

utf8::downgrade($str);
print length($str), "\n";
print $str, "\n";
```

When run in a utf8-configured terminal, this produces:

```
3
7
ಠ_ಠ
7
ಠ_ಠ
7
ಠ_ಠ
```

You can see that the (utf8-encoded) string is printed properly, and its length is unchanged, no matter whether its byte string is upgraded or downgraded.

**Comment by ams-tschoening** [comment]
> Incorrect. You can encode a UTF-8 byte string to UTF-8, the result is a different UTF-8 encoded byte string[...]

Feel free to find the error in my test:

    C:\Users\tschoening>perl -e "use Data::Dumper; use Encode ('from_to', 'decode', 'encode'); my $value = decode('CP-850', 'mööp'); $value = encode('UTF-8', $value); print(Dumper($value)); from_to($value, 'UTF-8', 'UTF-8'); print(Dumper($value))";
    $VAR1 = 'm├À├Àp';
    $VAR1 = 'm├À├Àp';

> Each step is still a perfectly valid Perl string[...]

"Perl string" implies character string and that is wrong, the result of encode is a byte array and that is documented:

> When you encode anything, the UTF8 flag on the result is always off, even when it contains a completely valid utf8 string.

https://perldoc.perl.org/Encode.html#encode

> When encoding the UTF-8 encoded bytes to UTF-8, you are considering them (as Perl does) as Unicode codepoints.

Because `encode` is expected to get a byte array and you tell it using source and target encoding how to handle that regarding characters and like my test shows, the result of the process is the same in the end. That totally makes sense and the only difference could occur because of Unicode normalization/denormalization.

> 3
> 7

That result is clearly proving what I'm saying all the time, in the first case Perl has a character string and therefore returns a length of 3 characters, in the second case it has a byte array and therefore returns a length of 7 bytes.

> You can see that the (utf8-encoded) string is printed properly, and its length is unchanged, no matter whether its byte string is upgraded or downgraded.

Your conclusion doesn't make sense because you wouldn't be able to explain why 3 is printed in the first row, either that is an error or there clearly is a distinction between byte arrays and characters. Rerun the test and print the result of `is_utf8` for alle cases as well. Additionally, that your string is printed propelry in your shell is as expected as well, because your shell of course doesn't care for Perl character strings vs. byte arrays but only gets bytes, those are valid UTF-8 and therefore render properly in all cases. That is as expected.

Consider the following instead in the docs for `upgrade` etc.:

> If $string is already stored as UTF-8, then this is a no-op.

**Comment by shadowcat-mst** [comment]
@tschoening I would strongly recommend reading your way through https://rt.cpan.org/Public/Bug/Display.html?id=104433 since it's rjbs (a perl5 pumpking for several releases) explaining how all of this actually works. Basically: the utf8 flag is not something you should ever, ever think is meaningful for this sort of purpose.

**Comment by ams-tschoening** [comment]
I already responded to that ticket and mentioned that the approach using `downgrade` is wrong:

https://rt.cpan.org/Ticket/Display.html?id=104433#txn-1790718

**Comment by shadowcat-mst** [comment]
@tschoening you are arguing, three years late, with people who understand the perl5 core better than you do. Your response is incoherent and your refusal to listen to the experts is becoming tiresome.

**Comment by karenetheridge** [comment]
> That result is clearly proving what I'm saying all the time, in the first case Perl has a character string and therefore returns a length of 3 characters, in the second case it has a byte array and therefore returns a length of 7 bytes.

No one (particularly me) ever claimed that strings were identical when they were encoded vs. decoded. They are different things. In my code snippet, the string starts out as three characters, some of which are represented by more than one byte: `x{0ca0}\x{5f}\x{0ca0}`. In the second, it is transformed into seven characters, now each only represented by a single byte, and therefore suitable for transmitting: `\x{e0}\x{b2}\x{a0}\x{5f}\x{e0}\x{b2}\x{a0}`.

Confusing encoding/decoding with upgrading/downgrading seems to be a big issue here.
The rest of your reply makes no sense unless you are confusing these concepts throughout.

**Comment by Grinnz** [comment]
> Feel free to find the error in my test:

Your test does not encode the string to UTF-8; it decodes it from UTF-8, and then encodes to UTF-8 again, obviously resulting in the same byte string. The operation of encoding a byte string to UTF-8 means to interpret it as a set of codepoints equal to the bytes it consists of, then encode *that* to UTF-8, and this is perfectly valid to do in Perl.

> "Perl string" implies character string and that is wrong, the result of encode is a byte array

No, Perl string implies a string in Perl. You are making a distinction that does not exist here. The result of encode is another Perl string consisting of the codepoint values equal to the bytes representing the input string in UTF-8 encoding. All strings in Perl are a set of codepoint values, and this is how you interact with them in Perl with functions such as substr, length, or regex matches. It is up to the user to know that the Perl string they are using represents the characters they intend, or an unequal byte representation of it in some encoding. How they are internally stored in C (the purpose of is_utf8, upgrade, and downgrade) is unrelated.

**Comment by redhotpenguin** [comment]
Hey folks, this thread seems to have gone off the rails here with ad hominem attacks and a lack of friendly discourse. I will need to take the step of locking the conversation.

Also just FYI, this repo has been deprecated in favor of https://github.com/redhotpenguin/perl-soaplite. The explanation is long and I'm not going to go into it here. If there are specific technical issues which you feel need to be addressed, I am more than happy to review pull requests at that repo.

Thanks!

**Pull request merged**
